### ISSUE TITLE
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1 when decoding kbin

### ISSUE THREAD

**Issue by JamesLewisLiu** [mon/kbinxml#10]
After running pip install lxml, it says `Successfully installed lxml-5.2.2`
Then I tried decoding and it shows this
```
Traceback (most recent call last):
  File "/usr/local/bin/kbinxml", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kbinxml/kbinxml.py", line 480, in main
    xml = KBinXML(input, convert_illegal_things=args.convert_illegal)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kbinxml/kbinxml.py", line 64, in __init__
    self.from_text(input)
  File "/usr/local/lib/python3.11/site-packages/kbinxml/kbinxml.py", line 73, in from_text
    self.xml_doc = etree.parse(BytesIO(input)).getroot()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3590, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1969, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1989, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1164, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 633, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 743, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 672, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```

I tried some of them but no lucks, here is raw bin
[mdbe.zip](https://github.com/mon/kbinxml/files/15297431/mdbe.zip)

**Comment by mon** [comment]
I don't know what this format is, but it's definitely not kbinxml - it's some bespoke format (similar to how IIDX has its own music db .bin format).
